# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.203
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build Metrics Library
      run: dotnet build Metrics --no-restore
    - name: Publish Metrics Library
      run: dotnet nuget push "Metrics/bin/*/*.nupkg" --source "github" --api-key ${{ secrets.NUGET_CRED }} --skip-duplicate
    
    - name: Add Source
      run: dotnet nuget add source https://nuget.pkg.github.com/EggnogII/index.json \
       --name github \
       --username EggnogII \
       --password ${{ secrets.NUGET_CRED }} \
       --store-password-in-clear-text

    - name: Test
      run: dotnet test --no-build --verbosity normal
